server:
  port: 8880

# 用来测试，从配置文件中读取信息的
test:
  hello: MyTestData

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wiki?useUnicode=true&characterEncoding=utf-8
    username: wiki
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# 整合Mybatis
mybatis:
  # ** 表示在mapper下不管有多少文件夹，都可以全部识别
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: top.faroz.pojo